### PR TITLE
vi-VN added translation

### PR DESCRIPTION
**Pull request by streetsamurai00mi**
I've translated distrochooser into vietnamese. Do you think that could be merged?
Should I do something more?

### CODE REVIEW

**Comment by cmllr** [comment]
Hey @streetsamurai00mi 

thank you very much for your contribution! It looks good so far, I will merge them with one of the next maintenance updates. Thank you for supporting the project!

**Comment by cmllr** [comment]
The patch just went online :)

**Comment by streetsamurai00mi** [comment]
Thanks a million for that 🎉

**Comment by cmllr** [comment]
Well, I have to thank 😁

**Pull request merged**
