### PR TITLE
Chinese translation

### PR DESCRIPTION
**Pull request by xingjiapeng**
I tried to translate distrochooser into zh-cn
Not done.

### CODE REVIEW

**Comment by xingjiapeng** [comment]
I have a question: what is "Datenschutzerklärung" in line 131?

**Comment by cmllr** [comment]
Hey @xingjiapeng!

Thank you for your contribution! (And sorry for my late response)

"Datenschutzerklärung" literally translates into "privacy policy".

**Comment by xingjiapeng** [comment]
Basically done, I guess.

**Comment by xingjiapeng** [comment]
Hello? Have I been forgotten? Thx!

**Comment by cmllr** [comment]
Hey, @xingjiapeng thank you for your translation!

I've been quite busy the last weeks, sorry for that.

I'll merge your translation now and it will be included with the next patches 😄

**Pull request merged**
